### ISSUE TITLE
Java socket get Property error. Local address/port is over-written by target address/port.

### ISSUE THREAD

**Issue by qiyuangong** [gramineproject/graphene#2046]
## Description of the problem
Java socket get Property error. Local address is over-written by target address. That's not good for Java socket connection.

## Steps to reproduce
Pls change `"10.239.158.65", 9000` into your local reachable address and port.

```java
import java.net.Socket;
import java.nio.channels.SocketChannel;
import javax.net.SocketFactory;
import java.nio.ByteBuffer;
import java.net.InetSocketAddress;
import java.io.IOException;

public class SocketFactTest {

    public static void main(String[] args) throws IOException {
        SocketFactory socketFactory = SocketFactory.getDefault();
        Socket socket = socketFactory.createSocket();
        //socketChannel.configureBlocking(false);
        socket.connect(new InetSocketAddress("10.239.158.65", 9000), 600);
        System.out.println("Conection successful!");
        System.out.println("Socket local port" + socket.getLocalPort());
        System.out.println("Socket port" + socket.getPort());
        System.out.println("Socket get local address" + socket.getLocalAddress());
        System.out.println("Socket get inet address" + socket.getInetAddress());
        socket.close();
    }
}
```

```bash
# normal
javac SocketFactTest.java
java SocketFactTest
# SGX
# create java.manifest.template
SGX=1 ./pal_loader /opt/jdk/java SocketFactTest
```

## Expected results
Conection successful!
Socket local port60046
Socket port9000
Socket get local address/10.239.166.29
Socket get inet address/10.239.158.65
## Actual results
Conection successful!
Socket local port9000
Socket port9000
Socket get local address/10.239.158.65
Socket get inet address/10.239.158.65

**Comment by llly** [comment]
This bug is caused by a series of URI create/parse mismatch.

see `shim_do_connect`:
In Graphene-SGX, `connect` with `socket(AF_INET,SOCK_STREAM,0)` is dispatched to
https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/Pal/src/host/Linux-SGX/db_sockets.c#L329-L340
`bind_addr` is pointer to `buffer` at the beginning. 
Then `socket_parse_uri`
https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/Pal/src/host/Linux-SGX/db_sockets.c#L202-L207
changes `bind_addr` to NULL.
After `ocall_connect`, **PAL_HANDLE with no `bind_addr` and only `dest_addr` is created.** https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/Pal/src/host/Linux-SGX/db_sockets.c#L358-L359

Go back to `shim_do_connect` 
https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/LibOS/shim/src/sys/shim_socket.c#L783-L789
In which `DkStreamGetName` is dispatched to
https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/Pal/src/host/Linux-SGX/db_sockets.c#L836
It gets pointers `bind_addr` and `dest_addr` without any checking
https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/Pal/src/host/Linux-SGX/db_sockets.c#L851-L856
and skips `bind_addr`
https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/Pal/src/host/Linux-SGX/db_sockets.c#L880-L881
creates an URI only `dest_addr`.
While `inet_parse_addr` always treat first URI as bind URI, and second as conn URI if exist.
https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/LibOS/shim/src/sys/shim_socket.c#L587
So `dest_addr` is stored to `sock->addr.in.bind`.  `&sock->addr.in.conn` is not changed.

Then see `shim_do_getsockname`:
https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/LibOS/shim/src/sys/shim_socket.c#L1521
It copies `sock->addr.in.bind`. But it is `dest_addr` instead of `bind_addr`.

**Comment by qiyuangong** [comment]
Thank you @llly for troubling shooting. That's very detail.👍 

Can we hotfix it with a few lines of changes?

**Comment by llly** [comment]
Here is a simple workaround to TCP connect. Not sure whether other socket functions need fixes.
https://github.com/llly/graphene/commit/5d5ec4ef0390df8cfeca9bcd2610fb65076643d8

**Comment by dimakuv** [comment]
Thanks @qiyuangong for reporting this bug, and thanks @llly for providing a workaround.

We will need to fix the whole address-parsing logic in Graphene. It is unnecessarily convoluted and leads to bugs like this.

**Comment by qiyuangong** [comment]
Hi @dimakuv . That's a good news! Thank you :)

Another good news:

After patching @llly 's patch, we can write/read from socket in this pipeline. It works well. 

Actually, this issue is related to HDFS read/write. HDFS use these socket APIs in IPC or client. After patching, we can read/write from HDFS.
